hufscheer/web

apps/manager/api/index.ts
apps/manager/middleware.ts

- closed #103 
- 유저 인증 정보에 따라 로그인 페이지 혹은 메인 페이지로 리다이렉트 합니다.
- next.js의 `middleware.ts`를 사용했습니다.
- <del>현재 백엔드 코드가 마무리 되지 않았지만 빠른 개발을 위해 코드가 수정되었음을 가정하고 작성했습니다. 추후 변경사항이 생기면 반영하도록 하겠습니다!</del>
- 수정 완료했습니다!

[FEAT] 유저 인증 정보에 따른 리다이렉션

---

apps/spectator/app/_components/GameFilter/GameFilter.css.ts
apps/spectator/components/Sidebar/index.tsx

- closed #150
- 헤더의 필터 탭 색상을 그레이 스케일로 변경합니다.

[STYLE] 헤더 스타일 수정

---

apps/spectator/app/game/[id]/_components/Banner/Banner.css.ts
apps/spectator/app/game/[id]/_components/CheerTalk/Banner/Banner.css.ts
apps/spectator/app/game/[id]/_components/CheerTalk/Banner/index.tsx
apps/spectator/app/game/[id]/_components/CheerTalk/Timeline/Timeline.css.ts
apps/spectator/app/game/[id]/_components/CheerTalk/Timeline/index.tsx
apps/spectator/app/game/[id]/_components/Timeline/Replacement.tsx
apps/spectator/app/game/[id]/_components/Timeline/Score.tsx
apps/spectator/app/game/[id]/_components/Timeline/Timeline.css.ts

- closed #154 
- 이슈와 동일
- 전반적으로 요소들의 크기와 배치를 와이어프레임에 맞게 수정했습니다.

[STYLE] 관객앱 경기상세/응원톡 UI 수정

---

apps/manager/app/game/[leagueId]/[gameId]/detail/page.tsx
apps/manager/constants/games.ts

- #157 
- `Select` 컴포넌트를 이용하여 쿼터를 드롭다운 메뉴로 설정 가능하게 변경했습니다. 
- `useForm`의 validate를 이용하여 폼 유효성 검사를 추가했습니다.

[FEAT] 경기 쿼터를 드롭다운 메뉴로 변경

---

apps/manager/api/game.ts
apps/manager/public/_redirects

- closed #170
- getTimeline API의 주소의 마지막에 slash 추가

[FIX] timeline api trailing slash 추가

---

apps/manager/app/game/[leagueId]/[gameId]/detail/page.tsx

- closed #172 
- 유튜브 경기 영상 base url 수정

[FIX] 유튜브 경기 영상 base url 수정

---

apps/manager/app/game/[leagueId]/[gameId]/timeline/[recordType]/page.tsx

- closed #174 
- Dayjs 타입을 Date 타입으로 수정합니다.

[FIX] 타임라인 날짜 선택 수정

---

apps/manager/components/Layout/Header/index.tsx

- closed #177 
- 불필요한 유저 아이콘 제거

[CHORE] 유저 아이콘 제거

---

apps/manager/app/game/[leagueId]/[gameId]/lineup/[teamId]/page.tsx

- closed #181 
- 라인업 등록 시 모든 선수를 한 번에 등록하거나, 한 번에 제거할 수 있는 버튼을 추가합니다.

[REFACTOR] 모든 선수 등록 및 제거 버튼 추가

---

apps/spectator/app/_components/GameList/index.tsx

- closed #186 
- round가 null인 경우 빈 문자열을 추가하고, number인 경우 형변환을 합니다.

[FIX] nullish round casting 에러 해결

---

apps/manager/api/league.ts
apps/manager/app/league/[leagueId]/team/[teamId]/page.tsx
apps/manager/app/league/[leagueId]/team/_components/TeamForm.tsx
apps/manager/hooks/mutations/useDeleteLeaguePlayerMutation.ts
apps/manager/hooks/mutations/useUpdateLeaguePlayersMutation.ts
apps/manager/hooks/queries/useLeagueTeamPlayersQuery.ts

- #185
- 대회 팀 선수가 추가되지 않는 오류를 해결했습니다.
- 대회 팀 선수 삭제 기능을 추가했습니다.
- 추가, 변경, 삭제 API가 모두 다르다보니 함수가 많아져서 추후에 분리해도 될 거 같아요.

[FIX] 대회 팀 선수 추가 오류 해결

---

apps/spectator/app/_components/GameFilter/RoundFilter.tsx
apps/spectator/app/_components/GameList/index.tsx
apps/spectator/app/page.tsx

- closed #194 
-  라운드 형변환 에러 해결
- optional string casting
- clickable 조건 수정
- leagueDetail.inProgressRound와 비교

[FIX] 라운드 형변환 및 clickable 조건 수정

---

apps/manager/hooks/mutations/useLoginMutation.ts
apps/manager/middleware.ts

- closed #206 
- 미들웨어에서 감지하는 URL에 trailing slash 옵션을 반영합니다.
- 로그인 성공 시 localStorage에 토큰을 저장하던 함수 제거

[FIX] middleware 정책 수정

---

apps/spectator/app/game/[id]/_components/CheerTalk/Form/Form.css.ts
apps/spectator/app/game/[id]/_components/CheerTalk/Form/index.tsx

- closed #210
- 인풋 박스의 양옆 공백 제거
- 응원톡 입력 시 전송 버튼 색상을 primary로 변경

[STYLE] cheer talk form 스타일 수정

---

apps/spectator/app/_components/GameFilter/GameFilter.css.ts
apps/spectator/app/_components/GameFilter/LeagueTeamFilter.tsx

- closed #212 
- 팀 필터의 캐럿 아이콘에 `position: absolute` 속성을 제거합니다.
- 팀 필터 캐럿 아이콘의 위치를 `float` 속성으로 고정합니다.
**기존**
**변경**

[FIX] 팀 필터 캐럿 아이콘 영역 문제 해결

---

apps/manager/types/game.ts
apps/manager/types/league.ts

- closed #216 
- GameLineupType number 타입에 null 추가

[FIX] 라인업 타입 수정

---

apps/spectator/app/game/[id]/_components/Banner/index.tsx

- #225 
- 출력 시간을 24시 형식으로 변경하였습니다.
- <img width="475" alt="image" src="https://github.com/hufscheer/client_v2/assets/97780352/8eeebb3f-e156-4e0b-b7c1-837f904bc557">

[FIX] 게임 시간 포맷팅 문제 해결

---

apps/spectator/app/_components/GameList/Button.tsx
apps/spectator/app/_components/GameList/Info.tsx
apps/spectator/app/game/[id]/_components/CheerTalk/EntryButton/index.tsx
apps/spectator/app/game/[id]/_components/CheerTalk/MenuModal/index.tsx
apps/spectator/app/game/[id]/_components/CheerTalk/index.tsx
apps/spectator/app/game/[id]/_components/CheerVS/TeamBox.tsx
apps/spectator/app/providers.tsx
apps/spectator/components/LeagueList/index.tsx
apps/spectator/components/Sidebar/index.tsx
apps/spectator/components/TeamLogo/index.tsx
apps/spectator/contexts/AmplitudeContext.tsx
apps/spectator/hooks/useTracker.ts
packages/ui/src/modal/index.tsx

- closed #227 
- 여전히 amplitude가 운영 환경에서 잘 동작하지 않습니다.
- 관련 자료를 발견하여 참고해서 다시 세팅합니다.
- https://github.com/Ianduha13/nextjs14-amplitude-integration/blob/main/components/ParticlesBg.jsx

[FIX] amplitude context 생성

---

apps/spectator/app/_components/GameList/Button.tsx
apps/spectator/app/_components/GameList/Info.tsx
apps/spectator/app/game/[id]/_components/CheerTalk/EntryButton/index.tsx
apps/spectator/app/game/[id]/_components/CheerTalk/MenuModal/index.tsx
apps/spectator/app/game/[id]/_components/CheerTalk/OnAir/index.tsx
apps/spectator/app/game/[id]/_components/CheerTalk/index.tsx
apps/spectator/app/game/[id]/_components/CheerVS/TeamBox.tsx
apps/spectator/app/game/[id]/page.css.ts
apps/spectator/app/providers.tsx
apps/spectator/components/LeagueList/index.tsx
apps/spectator/components/Sidebar/index.tsx
apps/spectator/components/TeamLogo/index.tsx
apps/spectator/contexts/AmplitudeContext.tsx
apps/spectator/hooks/useTracker.ts
apps/spectator/queries/useCheerTalkById.ts
apps/spectator/queries/useGameById.ts
packages/ui/src/modal/index.tsx

- closed #223 
- closed #227 
- closed #233
- amplitude 추가
- fix: 최대 응원하기 수 제한
- fix: 응원톡이 올라오며 비치는 버그 수정
- refactor: cheerTalk, gameBanner stale time 단축

[FIX] 유저 이벤트 분석 및 개선점 추가

---

pnpm-lock.yaml

- closed #257
- 의존성 버전 변경에 따른 `pnpm-lock.yaml` 파일 업데이트

[BUILD] update dependencies version

---

docs/storybook/stories/BottomSheet.stories.tsx
packages/ui/package.json
packages/ui/src/bottom-sheet/bottom-sheet.tsx
packages/ui/src/bottom-sheet/index.ts
packages/ui/src/bottom-sheet/styles.css.ts
packages/ui/src/index.ts
pnpm-lock.yaml

- #293
- bottom sheet 컴포넌트 추가
- 관련해서 `vaul` 패키지에 대한 의존성 추가

[FEAT] bottom sheet 컴포넌트 추가

---

pnpm-lock.yaml

[FIX] 누락된 lock 파일 추가

---

apps/manager/app/league/[leagueId]/[gameId]/timeline/_components/Form/PkForm.tsx
apps/manager/app/league/[leagueId]/[gameId]/timeline/_components/Form/ProgressForm.tsx
apps/manager/app/league/[leagueId]/[gameId]/timeline/_components/Form/ReplacementForm.tsx
apps/manager/app/league/[leagueId]/[gameId]/timeline/_components/Form/ScoreForm.tsx
apps/manager/app/league/[leagueId]/_components/LineupSheet/index.tsx
packages/ui/src/bottom-sheet/styles.css.ts
packages/ui/src/button/styles.css.ts

- #327
- 타임라인 등록 버튼을 여러 번 클릭 시 중복 호출되는 버그 발생

fix: 타임라인 등록 중복 호출 불가하게 수정

---

apps/manager/next.config.js
apps/spectator/next.config.js

- #334 
- `api.hufstreaming.site`을 `api.hufscheer.com` 으로 변경했습니다.

refactor: API 호출 주소 변경

---

apps/spectator/app/_components/GameList/Card.tsx
apps/spectator/app/_components/GameList/Info.tsx
apps/spectator/app/_components/GameList/styles.css.ts
apps/spectator/app/game/[id]/_components/Banner/Banner.css.ts
apps/spectator/app/game/[id]/_components/Banner/Skeleton.tsx
apps/spectator/app/game/[id]/_components/CheerVS/styles.css.ts
apps/spectator/app/game/[id]/page.css.ts
apps/spectator/app/layout.css.ts
apps/spectator/app/layout.tsx
apps/spectator/components/Layout/Header/styles.css.ts

- 이슈 번호
- 스켈레톤 UI 노출 시 레이아웃 시프트 발생하는 문제 해결
- 기본 스크롤바를 추가하여 레이아웃 시프트 해결
- 좌우 보더를 추가하여 컨텐츠 영역에 대한 구분
- 카드 링크의 범위를 수정하여 UX 개선

feat(spectator): 자잘한 변경사항 수정

---

.github/workflows/sync_spectator.yaml

chore: change ci scope

---

apps/spectator/app/analytics.tsx
apps/spectator/app/layout.tsx
apps/spectator/package.json
pnpm-lock.yaml

- 논의 결과에 따라 ga4 & gtm을 추가합니다.
- 배포 환경에서 태그가 정확하게 연결되었는지 확인해야 할 것 같아, 추후 수정이 필요할 수 있습니다.
- 분석툴 관련한 모듈을 분리했습니다.

feat(analytics): ga4 & gtm 추가

---

apps/spectator/app/game/[id]/_components/CheerTalk/CheerTalk.css.ts
apps/spectator/app/game/[id]/_components/CheerTalk/MenuModal/MenuModal.css.ts

- #367 
- #367에서 수정한 dialog 컴포넌트로 인한 렌더링 오류를 수정했습니다.

fix: dialog 사용 컴포넌트의 렌더링 오류 수정

---

apps/spectator/app/game/[id]/_components/Lineup/styles.css.ts
apps/spectator/app/game/[id]/_components/Participate/index.tsx
apps/spectator/app/game/[id]/_components/Participate/styles.css.ts
apps/spectator/app/game/[id]/_components/index.tsx
apps/spectator/app/game/[id]/page.css.ts
apps/spectator/app/game/[id]/page.tsx
apps/spectator/constants/configs.ts
packages/ui/src/tabs/Content.tsx
packages/ui/src/tabs/Tabs.css.ts

- 출전 탭을 추가하고, 게임 팀 로고가 찌그러지는 오류를 해결했습니다.

feat: 게임 페이지에 출전 탭 추가

---

apps/spectator/app/Providers.tsx
apps/spectator/components/Layout/Header/styles.css.ts
apps/spectator/package.json
pnpm-lock.yaml

- 관객 앱에서 페이지 전환 시 ProgressBar가 나타나도록 추가했습니다.

feat: 관객 앱 페이지 로딩 `ProgressBar` 추가

---

apps/manager/app/league/[leagueId]/[gameId]/component.tsx
apps/manager/app/league/[leagueId]/_components/GameForm/GameForm.tsx
apps/manager/app/league/[leagueId]/register-game/component.tsx

- Suspense 문제로 경기 생성 페이지가 접속되지 않는 오류를 해결합니다.

fix: 경기 생성 페이지가 접속되지 않는 오류 해결
