hufscheer/web

.github/workflows/chromatic.yaml
.gitignore
docs/storybook/package.json
docs/storybook/scripts/chromatic_publish.sh
docs/storybook/stories/Uploader.stories.tsx
docs/storybook/tsconfig.json
docs/storybook/turbo.json
package.json
packages/ui/src/image-uploader/index.tsx
packages/ui/src/image-uploader/styles.css.ts
pnpm-lock.yaml
turbo.json

- closed #15
- image uploader 컴포넌트 추가(storybook 배포 테스트를 위해 컴포넌트를 추가했습니다.)
- children으로 넣어준 요소 클릭 시 image를 추가할 수 있는 창이 생깁니다.
- 선택할 수 있는 이미지 파일의 확장자는 기본적으로 모든 확장자이며, `access` 속성을 통해 변경할 수 있습니다.
- image uploader 컴포넌트는 첫 번째 인자로 선택한 이미지의 url을, 두 번째 인자로 File 객체를 반환합니다.
- File 객체를 통해 선택한 파일의 파일명, 업데이트 날짜 등을 확인할 수 있습니다.
- 이미지 URL은 FileReader 객체를 통해 base64 형식으로 인코딩한 결과입니다.
- 복수의 이미지를 다뤄야 하는 경우, 혹은 drag & drop으로 이미지를 다뤄야 하는 경우(PC 대응)가 존재한다면 추후 수정하겠습니다.
- forwardRef를 통해 상위 컴포넌트에서 참조 정보를 내려주는 경우에 대응합니다.
- chromatic 설치
- 스토리북을 배포합니다.
- ci/cd가 자체적으로 존재하는 것으로 기억하여 별다른 actions를 추가하지 않고 PR을 작성했습니다.
- ci/cd가 동작하지 않는다면 workflows를 추가하도록 하겠습니다.
- File 객체 참고: https://developer.mozilla.org/ko/docs/Web/API/File
- FileReader.readAsDataURL: https://developer.mozilla.org/ko/docs/Web/API/FileReader/readAsDataURL
- …

[BUILD] chromatic으로 스토리북 배포

---

docs/storybook/stories/Toast.stories.tsx
docs/storybook/turbo.json
packages/ui/package.json
packages/ui/src/index.ts
packages/ui/src/toast/ToastItem.tsx
packages/ui/src/toast/ToastManager.tsx
packages/ui/src/toast/constants.ts
packages/ui/src/toast/hooks/useHover.ts
packages/ui/src/toast/hooks/useTimeout.ts
packages/ui/src/toast/index.tsx
packages/ui/src/toast/toast.css.ts
packages/ui/src/toast/type.ts
pnpm-lock.yaml

- closed #18
- Toast 컴포넌트 생성
- Toast instance를 import 한 뒤, show 메서드를 호출하여 토스트를 생성할 수 있습니다.
- 현재 디자인이 결정되지 않은 관계로 토스트를 여러 개 띄울 수 있도록 확장 가능하게 구현해두었습니다.
- 다만 UI는 하나만 띄울 수 있도록 구현해두었는데, 추후 디자인이 결정됨에 따라 수정이 필요하다면 개선하도록 하겠습니다. 
- toast item이 일정 시간 뒤 삭제될 수 있도록 id를 부여할 필요가 있는데, 이에 따라 고유한 식별자를 생성하는 `uuid` 라이브러리를 설치했습니다.
- 리액트에서 새로운 진입점(?)을 만들어주는 `createRoot` 메서드를 사용하기 위해 `react-dom` 라이브러리를 설치했습니다.
- Storybook package의 task 의존성 수정
- 현재 @hcc/ui의 코드가 수정되어도 즉각적인 re-build가 되지 않아 스토리북에서 이를 확인하려면 매번 `pnpm run build`를 실행해야 합니다.
- 이를 개선하기 위해 `@hcc/ui`에 `"dev": "tsc --watch"` 커맨드를 추가하고 task 의존성을 추가합니다.
- 추후 디자인 결정에 따라 변경사항이 생길 시 스타일 수정

[FEAT] Toast 컴포넌트 생성

---

.github/workflows/chromatic.yaml
docs/storybook/turbo.json
package.json
pnpm-lock.yaml

- closed #24
- Remote Cache 적용
- Vercel Remote Cache Store 활용
- 이 과정에서 팀원과 turbo 버전이 달라 캐시가 적용되지 않는 문제 발생
- 따라서 turbo version을 1.12.2로 맞춰줬음
- storybook pipeline scope 수정
- build 시 해시를 비교하기 위한 inputs을 명시함
- chromatic 배포 시 remote cache를 이용하기 위한 token 및 team id를 변수로 제공
- Remote Cache를 이용하기 위해 turbo 버전은 1.12.xx로 맞춰주세요.
- 훕치치 공용 계정으로 로그인
```bash
npx turbo login 
npx turbo link
```
- 로컬 캐시 삭제
```bash
rm -rf ./node_modules/.cache/turbo
```
- 빌드 테스트
```bash
pnpm build
```
- Remote Cache Enable 문구 확인

[PERF] Remote Cache 적용

---

packages/styles/src/theme.css.ts

- closed #35
- 와이어프레임에 의거하여 spaces token 추가
```ts
spaces: {
xxs: rem(4),
xs: rem(8),
sm: rem(12),
default: rem(16),
lg: rem(24),
xl: rem(32),
},
``
- 사이즈와 관련한 토큰 key에서 `xs`, `xl` 이상의 값은 숫자 대신 `x`를 하나씩 붙여 표현합니다.
- `2xs` -> `xxs`
- `2xl` -> `xxl`

[STYLE]: spaces 토큰 추가

---

apps/spectator/components/Sidebar/Sidebar.css.ts
apps/spectator/components/Sidebar/index.tsx
apps/spectator/components/layout/Header.css.ts
apps/spectator/components/layout/Header.tsx
packages/ui/src/modal/Trigger.tsx

- #61 
- Header 영역의 스타일과 아이콘 색상을 변경했습니다.
> <img width="334" alt="image" src="https://github.com/hufscheer/client_v2/assets/97780352/10316a45-62fe-4ff1-84db-0478bb028b5f">
- Sidebar Trigger 버튼에 수직 가운데 정렬을 추가하기 위해 모달 컴포넌트의 Trigger 영역을 수정했습니다.

[REFACTOR] Header 컴포넌트 스타일 변경

---

apps/manager/.eslintrc.js
apps/manager/app/layout.tsx
apps/manager/app/page.css.ts
apps/manager/app/page.tsx
apps/manager/next.config.js
apps/manager/package.json
apps/manager/postcss.config.js
apps/manager/styles/theme.ts
pnpm-lock.yaml

- closed #69
- @mantine 추가
- @mantine에 커스텀 색상을 추가하기 위해서는 항상 최소 10개의 배리에이션을 추가해야 하는 것으로 보입니다. 현재 훕치치에서 사용하고 있는 색상 베리에이션은 각각 6개이므로, 서로 호환이 되지 않는다는 문제가 있습니다.
- 때문에 @mantine에서 기본적으로 제공하는 `indigo varinats`를 primary color로 지정해두었습니다. `indigo`가 훕치치 primary color와 가장 흡사합니다. 참고로 위쪽이 훕치치의 primary color입니다.

[BUILD] @mantine 추가

---

apps/manager/api/auth.ts
apps/manager/app/layout.tsx
apps/manager/app/login/page.css.ts
apps/manager/app/login/page.tsx
apps/manager/app/page.css.ts
apps/manager/app/page.tsx
apps/manager/hooks/mutations/useLoginMutation.ts
apps/manager/package.json
apps/manager/types/auth.ts
pnpm-lock.yaml

- closed #72
- 로그인 기능 구현
- 로그인 시 form 컴포넌트를 사용합니다.
- 이외에도 매니저 어플리케이션에서는 다양한 정보를 제출하는 형태의 유저 시나리오가 많습니다.
- 이에 따라 `@mantine/form`을 설치하여 form 데이터를 보다 쉽고 간편하게 다룰 수 있도록 합니다.
- [@mantine/form](https://v5.mantine.dev/form/use-form/)
- 현재 `@hcc/ui`의 toast 컴포넌트가 내부에서 `document`를 사용하고 있기 때문에 빌드 시 에러가 발생합니다.
- 때문에 현재는 토스트 메시지 관련 코드를 제거한 채 올려두었습니다.
- 추후 toast 컴포넌트를 변경한다면 사용할 수 있을 것으로 보이고, 시간 여유가 없다고 판단하면 `@mantine/notification`와 같은 라이브러리를 사용하는 것도 좋아 보입니다.
- 이 부분은 필수 기능을 먼저 구현한 뒤 남은 시간에 따라 정해보면 좋을 것 같습니다!
- 쿼리 훅 함수 파일의 위치 변경을 제안합니다.
- 현재에는 쿼리 훅 함수를 `root/queries` 디렉토리에 두고 있습니다. 
- 하지만 내부에 query 함수와 mutation 함수가 혼재되어 있어 적절하지 못한 폴더명이라는 생각이 계속 들었습니다.
- 더욱이 queries 폴더 내에 정의해둔 hook 함수들 역시 query, mutation 함수를 일종의 hook 형태로 재정의한 것이고, 이를 통해 관련된 작업을 한 군데에 모아 처리할 수 있도록 한 것입니다. 이런 의도에서 `hooks/` 디렉토리 하위에 각각 …

[FEAT] manager login 기능 구현

---

apps/manager/.eslintrc.js
apps/manager/_redirects
apps/manager/api/index.ts
apps/manager/next.config.js
apps/manager/package.json
apps/spectator/_redirects
apps/spectator/api/game.ts
apps/spectator/api/index.ts
apps/spectator/next.config.js
apps/spectator/package.json

- #77 
- 관객 및 매니저 앱에 NextJS의 `rewrites` 기능을 이용하여 프록시를 적용했습니다. 
- `/api/:path*` 경로에 요청을 보내면 서버 통신이 이루어집니다.
- `process.env`를 사용하는 경우 매니저 앱에서 프록시 연결이 정상적으로 되지 않아(POST 요청이 아니라 GET 요청만 보내는 경우 존재) `next.config.js` 파일 내에 명시적으로 작성했습니다.
- 이에 따라 `.env` 파일이 사라져도 될 거 같습니다.
- 현재 관객 앱에서 `ECONNREFUSED` 로 인한 오류가 발생하고 있는데, 찾아보니 정상적이지 않은 URL로 연결을 할 때 발생한다고 하더라구요.
- 정상적이지 않은 URL로 연결 요청을 하는 경우 자동으로 'localhost:80' 으로 요청을 보내는데, 현재 관객 앱은 3000 포트에서 돌아가기 때문에, 80에 요청을 보내면 오류가 납니다.
- 서버에 올리면 포트가 같아지니 문제는 없지만, 어디서 오류가 발생하는 것인지 정확하게 찾으면 좋을 거 같습니다. 간단하게 API 사용하는 부분 훑어봤는데 아직 못 찾았습니다.

[BUILD] 관객 및 매니저 앱 프록시 연결

---

apps/manager/api/index.ts
apps/manager/next.config.js
apps/manager/public/_redirects
apps/spectator/api/index.ts
apps/spectator/next.config.js
apps/spectator/public/_redirects

- #90 
- 매니저 앱과 관객 앱에 적용되었던 프록시 환경을 제거했습니다.
- 구현된 프록시 환경으로는 관객 앱의 `Suspense`처리 및 CORS 문제를 완벽하게 해결하지 못하여, 기존의 환경으로 롤백하였습니다.

[BUILD] 프록시 환경 제거

---

apps/manager/api/index.ts
apps/manager/api/team.ts
apps/manager/app/ReactQueryProvider.tsx
apps/manager/app/league/[leagueId]/_components/LeagueMenuCard.tsx
apps/manager/app/league/[leagueId]/page.tsx
apps/manager/app/league/[leagueId]/team/_components/ActionIcon/ActionIcon.css.ts
apps/manager/app/league/[leagueId]/team/_components/ActionIcon/index.tsx
apps/manager/app/league/[leagueId]/team/page.tsx
apps/manager/app/league/_components/LeagueCard/index.tsx
apps/manager/components/Card/index.tsx
apps/manager/hooks/queries/useLeagueTeamQuery.ts
packages/icons/src/index.ts
packages/icons/src/svg/subtract.svg

- closed #94 
- 리그 팀 관리 페이지를 생성했습니다.
- league team 삭제 쿼리가 아직 없어서 일단은 `alert`로 대체해두었습니다.
- card content의 다형성을 보장합니다.
- axios response interceptor가 개발 단계에서는 불필요하다고 판단했고, 추후 에러 바운더리로 더 세밀하게 에러 처리를 하면 좋을 것 같아 일단은 제거해두었습니다. 
- 대회 팀이 없는 경우는 추후 다듬으면 좋을 것 같습니다.

[FEAT] 리그 팀 관리 페이지 생성

---

apps/spectator/app/game/[id]/_components/CheerTalk/CheerTalk.css.ts
apps/spectator/app/game/[id]/_components/CheerTalk/Form/Form.css.ts
apps/spectator/app/game/[id]/_components/CheerTalk/Form/index.tsx
apps/spectator/app/game/[id]/_components/CheerTalk/List/List.css.ts
apps/spectator/app/game/[id]/_components/CheerTalk/List/index.tsx

- #97 
- 응원톡 모달의 높이를 적절히 조절해 모바일 브라우저 화면 안에 모든 요소가 정상적으로 보이도록 수정했습니다.
- 응원톡 스크롤 하단 버튼을 수정했습니다.
- 스타일: 불투명도와 그림자를 추가해 응원톡과 겹칠 때 구분이 되도록 하였습니다.
- 스크롤을 올렸을 때만 노출되도록 조건부 함수를 추가했습니다.
- 응원톡 작성 폼의 영역을 소폭 조정해 응원톡과 너무 벌어지지 않도록 고쳤습니다.
- 
https://github.com/hufscheer/client_v2/assets/87803596/b4a6689f-b272-4965-84f1-c9b755b484b2
- 오늘 슬랙에 언급했던 `Runtime.UnhandledPromiseRejection: Error: Either brokerURL or webSocketFactory must be provided` 문제는 좀 더 서치가 필요합니다. 새로고침 시 brokerURL에 넘겨주는 웹소켓 주소가 유실돼 발생하는 문제이므로 새로고침에도 웹소켓 주소를 잃지 않는 방법을 찾아야할 것 같습니다.

[STYLE] 관객 응원톡 사용성 향상

---

apps/spectator/app/_components/GameFilter/LeagueTeamFilter.tsx

- closed #105 
- 게임 목록의 리그 팀 리스트 필터를 쿼리 키로 등록할 때, 정렬된 값을 추가합니다.
- 이 때, 쿼리 키 값이 '2,5,8,11,13,15'과 같이 문자열로 등록되는데, 라이브러리 내부에서 단순 일치 연산으로 쿼리 키를 비교하고 있습니다. 그래서 ['2', '5', ... ]처럼 배열로 비교하는 것에 비해 오히려 성능이 좋을 것 같아 그대로 추가했습니다.

[PERF] 게임 목록 쿼리 키 정렬

---

apps/manager/api/league.ts
apps/manager/app/league/register/_components/LeagueInfo/index.tsx
apps/manager/app/league/register/_components/LeagueTeam/index.tsx
apps/manager/app/league/register/_components/LeagueTeamPlayers/index.tsx
apps/manager/app/league/register/page.tsx
apps/manager/hooks/mutations/useCreateLeagueTeamMutation.ts
apps/manager/types/league.ts

- closed #111 
- 대회 팀 생성 시 FormData를 입력 받도록 구현합니다.
- 현재 register의 flow가 와이어 프레임과 다릅니다.
- 대회 팀과 팀 선수를 일괄적으로 생성하도록 구현이 되어 있는데, step의 기능을 잘 이용하면 쉽게 수정이 가능하지 않을까 합니다.
- 대회 팀을 생성하면 step을 3번으로 옮겨 대회 팀 선수를 생성하도록 합니다.
- 대회 팀 선수 생성이 마무리 되면 다시 2번으로 옮겨 대회 팀을 생성하도록 합니다.
- 걱정되는 것은 컴포넌트가 언마운트 되기 때문에 기존에 생성했던 대회 팀이 UI 상에는 표시되지 않을 수도 있겠네요. 
---
위에서 언급한대로 플로우 수정해뒀습니다.
`TODO`
- 아예 대회 팀은 여러 개를 한 번에 생성할 수 없다고 이해하기
- 대회 팀이 생성되면 생성된 대회 팀 id를 response로 넘겨달라고 백엔드 팀원에게 요청하기
- api가 수정되면 대회 팀 생성 성공 시 handleTeamId로 현재 teamId 변경
- teamId를 LeagueTeamPlayers 컴포넌트에 전달한 뒤 createLeaguePlayersMutation hook 호출

[REFACTOR] 대회 팀 생성 API 수정

---

apps/manager/api/league.ts
apps/manager/app/league/register/_components/Confirm/index.tsx
apps/manager/app/league/register/_components/LeagueInfo/index.tsx
apps/manager/app/league/register/_components/LeagueTeam/index.tsx
apps/manager/app/league/register/_components/LeagueTeamPlayers/index.tsx
apps/manager/app/league/register/page.tsx

- closed #113 
- 대회 팀 선수 생성 기능 구현
- 대회 등록 플로우를 종료하고자 하면 우측 상단에 완료 버튼 클릭
- 모달을 통해 재확인
- 대회 팀을 생성하면 대회 팀 선수 스텝으로 이동
- 대회 팀 선수 등록을 마무리 하면 다시 대회 팀 생성 스텝으로 이동
- 와이어 프레임과 플로우가 조금 다른데, API로 넘겨 받는 데이터로 작업을 동기적으로 해야 해서 일단 이렇게 구현했습니다.
- 대회 생성 성공 시 대회 id 발급
- 발급 받은 대회 id로 대회 팀 생성
- 대회 팀 생성 성공 시 대회 팀 id 발급
- 발급 받은 대회 팀 id로 대회 팀 선수 생성
- 대회 선수를 제거하는 버튼 클릭 시 기존에 작성되었던 선수 번호가 중복해서 등록되는 버그가 있습니다.
- 현재 input의 mapping key를 index로 관리하기 때문인 것 같네요.
- 추후 `uuid` 같은 라이브러리로 고유 식별자를 생성해주는 방법을 고려할 수 있겠습니다.
- 필요하다면 리뷰 반영하면서 추가해서 올려보도록 하겠습니다.

[FEAT] 대회 팀 선수 생성 기능 구현

---

apps/manager/api/league.ts
apps/manager/app/league/[leagueId]/game/page.tsx
apps/manager/app/league/[leagueId]/loading.tsx
apps/manager/app/league/[leagueId]/team/[teamId]/page.tsx
apps/manager/app/league/[leagueId]/team/_components/TeamForm.tsx
apps/manager/app/league/[leagueId]/team/page.tsx
apps/manager/app/league/[leagueId]/team/register/page.tsx
apps/manager/hooks/mutations/useUpdateLeagueTeamMutation.ts
apps/manager/hooks/mutations/useUpdateLeagueTeamPlayersMutation.ts
apps/manager/hooks/queries/useLeagueTeamDetailQuery.ts
apps/manager/hooks/queries/useLeagueTeamPlayersQuery.ts
apps/manager/types/league.ts

- #110 
- 매니저 앱의 대회 팀 관리를 구현했습니다.
- 팀 리스트
- 팀 리스트 편집 (삭제)
- 팀 추가, 팀 선수 추가
- 팀 자세히 보기 및 수정
- 현재 팀 추가 및 선수 추가 부분이 대회 생성 시 사용하는 폼과 유사합니다. 리팩토링 시 하나의 파일로 관리하면 좋을 듯 합니다.

[FEAT] 매니저 앱 대회 팀 관리 구현

---

apps/spectator/app/layout.tsx
apps/spectator/components/layout/Header.css.ts

- #116 
- 헤더의 높이와 배경 색상을 변경했습니다.
- Viewport를 추가하여 iOS 기기의 상단바 색상을 변경했습니다.

[STYLE] 관객 앱 레이아웃 스타일 변경

---

apps/spectator/app/_components/GameFilter/LeagueTeamFilter.tsx

- closed #129 
- QA 도중 팀 필터를 등록한 뒤 모두 제거했다가, 다시 등록하면 전체 팀의 경기 목록을 뿌려주어야 하는데, 아무런 값도 들어가지 않은 것을 확인했습니다.
- 살펴보니 쿼리 파라미터로 관리하는 필터에 값이 아무것도 존재하지 않으면 빈 문자열이 들어가는데, 이 빈 문자열이 searchParams에 의해 파싱 될 때 0으로 변환되고 있었습니다.
- 따라서 필터의 값이 아무것도 존재하지 않을 시 빈 문자열이 아니라 쿼리 파라미터 자체를 제거하도록 수정합니다.

[FIX]: 사용하지 않는 query parameter 제거

---

apps/spectator/app/_components/GameFilter/GameFilter.css.ts
apps/spectator/app/_components/GameFilter/RoundFilter.tsx

- #135 
- 라운드 필터에 `roundFilterDisabled` 스타일을 추가하고, `Link` 컴포넌트를 조건부로 출력하게 변경했습니다.
- <img width="373" alt="image" src="https://github.com/hufscheer/client_v2/assets/97780352/aa5acaff-7303-4772-920f-6503d9388907">

[FEAT] 진행 전 라운드 비활성화

---

apps/spectator/components/LeagueList/index.tsx
apps/spectator/queries/useLeague.ts
apps/spectator/queries/useLeagueArchives.ts

- closed #137 
- 사이드바에서 제공하는 리그의 범위를 **[진행 중인 대회 제외]**에서 **[모든 대회]**로 재설정합니다.
- 진행되었던 모든 경기를 보관한다는 의미에서 hook 함수의 명칭을 `useLeagueArchives`로 변경합니다.

[REFACTOR] 사이드바 리그 범위 재설정

---

apps/spectator/app/game/[id]/_components/CheerTalk/Timeline/index.tsx
apps/spectator/queries/useTimelineById.ts

- closed #139 
- 응원톡 상단 타임라인이 가장 오래된 정보를 제공하고 있습니다. 이를 수정합니다.
- 실시간성을 어느정도 보장하기 위해 다음과 같은 옵션을 추가합니다.
- 1분에 한 번 refetch
- window focus 시 refetch
- reconnect 시 refetch
- 컴포넌트 mount 시 refetch
- stale time 1분으로 단축

[FIX] 응원톡 상단 타임라인 수정

---

apps/manager/app/_components/PlayingCard/index.tsx

- #143 
- 기존의 응원톡 버튼을 라인업 버튼으로 변경하고, 이에 따른 링크 이동을 변경했습니다.

[FEAT] 진행중 경기 카드에 라인업 이동 버튼 추가

---

apps/manager/app/game/[leagueId]/[gameId]/timeline/[recordType]/page.tsx
apps/manager/app/league/[leagueId]/detail/_components/Forms.tsx
apps/manager/app/league/[leagueId]/game/register/page.tsx
apps/manager/app/league/register/_components/LeagueInfo/index.tsx
apps/manager/utils/time.ts

- #145 
- `convertToServerTime` 함수를 추가하여, 서버에 시간 전송 시 한국 시간으로 전달할 수 있게 변경했습니다.
- 대회 팀 생성 부분에서, 종료 시각이 시작 시각을 넘어갈 수 있는 문제를 해결했습니다. 
- 대회 생성 시 '축구' 종목을 기본적으로 선택되게 하고, 종목 선택 박스를 보이지 않게 했습니다. 
- 타임라인, 게임 생성 부분에 함수를 적용했습니다. 서버로 시간을 넘기는 부분이 더 있다면 반영하도록 하겠습니다.

[FIX] 서버 시간 동기화 문제 해결

---

apps/spectator/app/game/[id]/_components/Highlight/index.tsx

- closed #152 
- 쿼리 훅 함수의 반환값으로 전달 받는 data는 videoId라는 key를 갖는 객체입니다. 하지만 이를 그대로 사용하고 있어, 에러가 발생하고 있습니다.
- 이를 해결합니다.
기존
```ts
const { data: videoId } = useVideoQuery(gameId);
`youtube.com/~~~~~/${videoId}`
```
변경
```ts
const { data: info} = useVideoQuery(gameId);
`youtube.com/~~~~~/${info.videoId}`
```

[FIX] 잘못된 video id 수정

---

apps/spectator/app/_components/GameList/Button.tsx
apps/spectator/app/_components/GameList/Card.tsx
apps/spectator/app/_components/GameList/Metadata.tsx
apps/spectator/app/game/[id]/_components/CheerTalk/Item/index.tsx
apps/spectator/app/game/[id]/_components/CheerVS/TeamBox.tsx
apps/spectator/app/game/[id]/_components/Lineup/Captain.tsx
apps/spectator/app/game/[id]/_components/Lineup/PlayerList.tsx
apps/spectator/app/game/[id]/page.tsx
apps/spectator/app/page.tsx
apps/spectator/constants/configs.ts
apps/spectator/constants/gameStatus.ts
apps/spectator/types/game.ts

- closed #141
- 경기 영상 탭으로 이동할 수 있는 버튼을 추가합니다.
- 각종 타입을 공통으로 관리할 수 있도록 수정합니다.
- 상수 파일을 일괄적으로 관리합니다.

[FEAT] 경기 영상 버튼 추가

---

apps/manager/app/game/[leagueId]/[gameId]/detail/page.tsx
apps/manager/app/league/[leagueId]/detail/_components/Forms.tsx
apps/manager/app/league/[leagueId]/detail/page.tsx
apps/manager/app/league/register/_components/LeagueInfo/index.tsx
apps/manager/types/league.ts

- #148
- 대회 정보 관리 페이지 진입 시 폼에 리그 데이터를 삽입하도록 변경했습니다.
- 종목은 4(축구)로 고정하였으며, 진행중인 라운드(inProgressRound)를 추가했습니다. 
- 경기 수정 부분에 #147 PR에서 놓친 부분을 수정했습니다. 
- 폼 데이터 타입과 initial data를 `types/form.ts` 과 같은 파일에서 변수로 관리하면 어떨까요?

[FIX] 대회 정보에 종목과 라운드가 보이지 않는 문제 해결

---

apps/spectator/app/_components/GameList/index.tsx
apps/spectator/app/page.tsx

- #162 
- 현재 initial round query parameter가 제대로 반영되고 있지 않습니다.
- 대회가 현재 진행 중이라면(isInProgress) 현재 진행 중인 라운드(inProgress)를, 그렇지 않다면 최대 라운드(maxRound)를 추가합니다.
round query parameter가 없어도 기존에 포함되어 있던 결승 게임 정보가 표시되지 않습니다.

[FIX] 초기 라운드 쿼리 반영

---

apps/spectator/app/_components/Live/index.tsx
apps/spectator/app/game/[id]/_components/CheerVS/index.tsx
apps/spectator/app/game/[id]/page.tsx
apps/spectator/types/game.ts

- #164 
- 경기 state가 `PLAYING`인지 확인하여, Live 컴포넌트를 조건부로 표시하도록 구현했습니다. 
- Live 컴포넌트의 경우 오류, 로딩을 엄격하게 관리하지 않아도 생각되어 `<></>`를 추가했습니다.

[FIX] Live 아이콘 표시 여부 수정

---

apps/manager/api/league.ts
apps/manager/app/league/[leagueId]/team/[teamId]/page.tsx
apps/manager/app/league/[leagueId]/team/_components/TeamForm.tsx
apps/manager/app/league/[leagueId]/team/page.tsx
apps/manager/app/league/[leagueId]/team/register/page.tsx
apps/manager/app/league/register/_components/LeagueTeamPlayers/index.tsx
apps/manager/app/league/register/page.tsx
apps/manager/hooks/mutations/useCreateLeagueTeamMutation.ts
apps/manager/hooks/mutations/useDeleteLeagueTeamMutation.ts
apps/manager/hooks/mutations/useUpdateLeagueTeamPlayersMutation.ts
apps/manager/hooks/queries/useLeagueTeamQuery.ts
apps/manager/types/league.ts

- #167
- 대회 팀 삭제 기능을 추가했습니다.
- 대회 팀 정보 페이지에 팀 로고가 나타나지 않는 오류를 해결했습니다. 
- 팀 선수의 등번호와 이름이 변경되지 않는 오류를 해결했습니다. 
- 대회 생성 페이지에서 '대회 로고' 텍스트를 '팀 선수'로 변경했습니다.
- 대회 팀 업데이트 API가 명세와 다르게 동작하고 있어, 로고 변경을 하지 않으면 팀 이름이 변경되지 않습니다. 이 부분은 백엔드 쪽에서 해결하면 같이 해결될 거 같습니다.

[FEAT] 대회 팀 관리에 삭제 기능 추가 및 로고 수정

---

apps/manager/app/page.tsx

- #179
- 매니저 메인 페이지의 경기 관리 버튼을 삭제했습니다.

[CHORE] 관리자 메인 페이지의 게임 버튼 제거

---

apps/manager/constants/games.ts

- closed #183 
- games.ts의 SPORTS 배열에 축구를 제외한 나머지 스포츠 목록을 제거했습니다. 

[REFACTOR] 불필요한 스포츠 상수 제거

---

apps/manager/app/league/[leagueId]/game/_components/GameCard.tsx

- close #191 
- 대회 경기 관리 페이지에서 응원톡 대신 해당 경기의 라인업 관리 페이지로 이동할 수 있는 링크를 추가합니다.

[CHORE] 응원톡 제거 후 라인업 링크 추가

---

apps/spectator/api/league.ts
apps/spectator/app/_components/GameFilter/RoundFilter.tsx
apps/spectator/app/_components/GameList/index.tsx
apps/spectator/app/page.tsx
apps/spectator/queries/useLeagueDetail.ts
apps/spectator/types/league.ts

- closed #188 
- 리그 상세 API 및 쿼리를 추가합니다.
- 선택된 리그의 라운드 정보에 따라 라운드 탭을 재구성합니다.

[FIX] 리그 별 라운드 정보 반영

---

apps/spectator/app/game/[id]/_components/Banner/Banner.css.ts
apps/spectator/app/game/[id]/_components/CheerTalk/Banner/Banner.css.ts
apps/spectator/app/game/[id]/_components/CheerTalk/EntryButton/EntryButton.css.ts
apps/spectator/app/game/[id]/_components/CheerTalk/Fallback/Fallback.css.ts
apps/spectator/app/game/[id]/_components/CheerTalk/Form/Form.css.ts
apps/spectator/app/game/[id]/_components/CheerTalk/Item/Item.css.ts
apps/spectator/app/game/[id]/_components/CheerTalk/OnAir/OnAir.css.ts
apps/spectator/app/game/[id]/_components/CheerTalk/OnAir/index.tsx
apps/spectator/app/game/[id]/_components/Lineup/Lineup.css.ts
apps/spectator/package.json
pnpm-lock.yaml

- #160 
- 경기 상세페이지 상단 배너 팀명이 긴 경우 말줄임표가 되도록 하였습니다.
- 응원톡 상단 배너에 경기 쿼터(시작 전 등) 글자가 쪼개지지 않도록 `whiteSpace: 'nowrap'` 을 추가했습니다.
- 경기 상세페이지 라인업의 주장 표시에 응원톡 엔트리버튼이 묻히는 현상을 zIndex 추가로 해결했습니다.
- 경기 상세페이지 실시간 응원톡이 업데이트 될 때 spring 애니메이션을 추가했습니다.
- spring 애니메이션의 경우 애니메이션 자체는 만족스러우나, 이전 응원톡이 위로 밀려나고 새 응원톡이 아래에서 올라오도록 제작하고 싶었지만 시간 문제로 우선 새 응원톡이 갱신될 때마다 새롭게 아래에서 튀어나오는 정도로만 제작했습니다.

[STYLE] 관객 앱 UI 개선

---

apps/manager/app/game/[leagueId]/[gameId]/detail/page.tsx

- #198 
- 게임 기본 정보 수정 페이지에서 일부 데이터가 잘못 설정되어 저장되지 않는 오류를 수정했습니다. 
- `videoId`가 `null`일 경우, 유튜브 prefix가 적용되지 않도록 수정했습니다. 
- 유튜브 링크가 유효하지 않는 경우(videoId에 입력 존재) 텍스트를 출력하도록 변경했습니다.
- 오류로 인해 저장이 이루어지지 않은 경우 대화 상자가 표시되도록 구현했습니다.

[FIX] 매니저 게임 기본 정보 저장 오류 해결

---

apps/manager/app/game/[leagueId]/[gameId]/timeline/[recordType]/_components/ReplacementRecord/index.tsx

- #196 
- 타임라인 수정 시 IN, OUT 선수가 반대로 적용되는 오류를 수정했습니다.

[FIX] 매니저 타임라인 IN-OUT 오류 수정

---

apps/spectator/app/game/[id]/_components/Banner/Banner.css.ts
apps/spectator/app/game/[id]/_components/Banner/Error.tsx
apps/spectator/app/game/[id]/_components/CheerTalk/Fallback/index.tsx
apps/spectator/app/game/[id]/_components/CheerVS/Error.tsx
apps/spectator/app/game/[id]/_components/Highlight/Fallback.tsx
apps/spectator/app/game/[id]/_components/Highlight/Highlight.css.ts
apps/spectator/app/game/[id]/_components/Lineup/Fallback.tsx
apps/spectator/app/game/[id]/_components/Lineup/Lineup.css.ts
apps/spectator/app/game/[id]/_components/Timeline/Fallback.tsx
apps/spectator/app/game/[id]/_components/Timeline/Timeline.css.ts
apps/spectator/app/game/[id]/_components/Timeline/index.tsx
apps/spectator/queries/useGameLineupById.ts
apps/spectator/queries/useVideoQuery.ts

- #200 
- 관객 게임 페이지의 가이드 텍스트를 변경하였습니다. 
- [연결이 원활하지 않습니다.], [해당 경기의 선수 선발명단 업데이트 전입니다.] 등 와이어프레임을 반영하여 `ErrorFallback` 영역의 스타일 및 텍스트를 변경하였습니다.

[REFACTOR] 관객 가이드 텍스트 형식 변경

---

apps/spectator/app/_components/GameFilter/GameFilter.css.ts

- closed #160
- 대회 팀 필터의 배경이 와이어프레임과 달라 일치시켜줬습니다.

[STYLE] 대회 팀 필터 배경 그라데이션 적용

---

apps/manager/api/game.ts
apps/manager/app/game/[leagueId]/[gameId]/lineup/[teamId]/_components/PlayerCard/index.tsx
apps/manager/app/game/[leagueId]/[gameId]/lineup/[teamId]/page.tsx
apps/manager/hooks/mutations/useCreateLineupMutation.ts
apps/manager/next.config.js
apps/manager/types/game.ts
apps/manager/types/league.ts
apps/manager/types/utils.ts

- closed #189
- 외부 리소스 주소(github.com)를 허용합니다.
- 라인업 관련 타입을 재정의합니다.
- 이제 라인업 수정 페이지에 진입 시 기존 라인업은 **선발** 탭에 표시되고, 라인업을 수정할 시 추가되는 것이 아니라 덮어씌어집니다.

[FIX] 라인업 수정 기능 개선

---

apps/spectator/app/game/[id]/_components/CheerTalk/OnAir/index.tsx
apps/spectator/app/game/[id]/_components/CheerVS/TeamBox.tsx
apps/spectator/app/game/[id]/page.css.ts
apps/spectator/queries/useCheerTalkById.ts
apps/spectator/queries/useGameById.ts

- closed #223 
- 최대 응원 수(500)을 초과할 시 alert을 띄우며 응원하기 수를 제한합니다.
-  On Air의 응원톡이 올라오면서 탭 컴포넌트 배경에 비치는 버그를 수정합니다.
- cheerTalk, gameDetail의 stale time을 단축합니다.
- 소켓으로 데이터를 쌓다가 페이지 전환이 발생하면 해당 데이터는 소멸합니다.
- 이 때 응원톡에 대한 쿼리 캐시가 남아 있다면 그 사이에 발생한 응원톡이 누락된 것처럼 보입니다. 이를 해결하기 위해 응원톡의 쿼리 캐시를 제거합니다.
- gameDetail은 게임 상세 페이지의 배너에 사용되는 데이터입니다.
- 이는 타임라인과 싱크를 맞춰야 할 필요가 있다 판단했습니다.
- 때문에 타임라인과 마찬가지로 1분마다 polling합니다.

[FIX] 실 사용 후 문제점 개선

---

apps/spectator/app/_components/GameFilter/GameFilter.css.ts
apps/spectator/app/_components/GameFilter/LeagueTeamFilter.tsx
apps/spectator/app/_components/GameList/Button.tsx
apps/spectator/app/_components/GameList/Info.tsx
apps/spectator/app/game/[id]/_components/CheerTalk/EntryButton/index.tsx
apps/spectator/app/game/[id]/_components/CheerTalk/Item/Item.css.ts
apps/spectator/app/game/[id]/_components/CheerTalk/Item/index.tsx
apps/spectator/app/game/[id]/_components/CheerTalk/MenuModal/MenuModal.css.ts
apps/spectator/app/game/[id]/_components/CheerTalk/MenuModal/index.tsx
apps/spectator/app/game/[id]/_components/CheerTalk/OnAir/index.tsx
apps/spectator/app/game/[id]/_components/CheerTalk/index.tsx
apps/spectator/app/game/[id]/_components/CheerVS/TeamBox.tsx
apps/spectator/app/game/[id]/page.css.ts
apps/spectator/app/providers.tsx
apps/spectator/components/LeagueList/index.tsx
apps/spectator/components/Sidebar/index.tsx
apps/spectator/components/TeamLogo/index.tsx
apps/spectator/contexts/AmplitudeContext.tsx
apps/spectator/hooks/useTracker.ts
apps/spectator/queries/useCheerMutation.ts
apps/spectator/queries/useCheerTalkById.ts
apps/spectator/queries/useGameById.ts
packages/ui/src/modal/index.tsx

- closed #235 
- 한 번 응원하기 요청을 보내면 여러 번 중복해서 응원하기 요청이 발생하는 버그를 제거합니다.
- 원인은 낙관적 업데이트 때문으로 보이며, 쿼리가 발생할 때마다 cheer count를 강제로 변경해주고 있는데 이 부분에서 상태 변경이 감지되어 디바운싱이 시작되고, 그래서 중복 요청이 발생한 것으로 보입니다.
- 자세한 내용은 조금 더 알아봐야 할 것 같습니다.

[FIX] cheer count 중복 요청 버그 수정

---

apps/spectator/app/_components/GameFilter/GameFilter.css.ts
apps/spectator/app/_components/GameFilter/LeagueTeamFilter.tsx
apps/spectator/app/_components/GameList/Button.tsx
apps/spectator/app/_components/GameList/Info.tsx
apps/spectator/app/game/[id]/_components/CheerTalk/EntryButton/index.tsx
apps/spectator/app/game/[id]/_components/CheerTalk/Item/Item.css.ts
apps/spectator/app/game/[id]/_components/CheerTalk/Item/index.tsx
apps/spectator/app/game/[id]/_components/CheerTalk/MenuModal/MenuModal.css.ts
apps/spectator/app/game/[id]/_components/CheerTalk/MenuModal/index.tsx
apps/spectator/app/game/[id]/_components/CheerTalk/OnAir/index.tsx
apps/spectator/app/game/[id]/_components/CheerTalk/index.tsx
apps/spectator/app/game/[id]/_components/CheerVS/TeamBox.tsx
apps/spectator/app/game/[id]/page.css.ts
apps/spectator/app/providers.tsx
apps/spectator/components/LeagueList/index.tsx
apps/spectator/components/Sidebar/index.tsx
apps/spectator/components/TeamLogo/index.tsx
apps/spectator/contexts/AmplitudeContext.tsx
apps/spectator/hooks/useTracker.ts
apps/spectator/queries/useCheerMutation.ts
apps/spectator/queries/useCheerTalkById.ts
apps/spectator/queries/useGameById.ts
packages/ui/src/modal/index.tsx

- closed #235 
- 한 번 응원하기 요청을 보내면 여러 번 중복해서 응원하기 요청이 발생하는 버그를 제거합니다.
- 원인은 낙관적 업데이트 때문으로 보이며, 쿼리가 발생할 때마다 cheer count를 강제로 변경해주고 있는데 이 부분에서 상태 변경이 감지되어 디바운싱이 시작되고, 그래서 중복 요청이 발생한 것으로 보입니다.
- 자세한 내용은 조금 더 알아봐야 할 것 같습니다.

[FIX] cheer count 중복 요청하는 버그 수정

---

apps/spectator/app/_components/GameList/Button.tsx
apps/spectator/app/_components/GameList/Info.tsx
apps/spectator/app/game/[id]/_components/CheerTalk/EntryButton/index.tsx
apps/spectator/app/game/[id]/_components/CheerTalk/MenuModal/index.tsx
apps/spectator/app/game/[id]/_components/CheerTalk/index.tsx
apps/spectator/app/game/[id]/_components/CheerVS/TeamBox.tsx
apps/spectator/components/LeagueList/index.tsx

- closed #238 
- 이벤트명을 기능 별로 통일합니다.
ex)
```ts
// cheerVS
tracker(`cheerVS ${gameTeamName}(${gameId})`, {
clickEvent: `${count - cheerCount}`,
});
// gameList
onClick={() =>
tracker(`gameList`, { clickEvent: `${gameId} ${state} game card` })
}
```
이제 다음과 같이 이벤트를 모아서 확인할 수 있습니다.

[FIX] amplitude event name 재설정

---

apps/spectator/app/_components/GameList/Button.tsx
apps/spectator/app/_components/GameList/Info.tsx
apps/spectator/app/game/[id]/_components/CheerTalk/EntryButton/index.tsx
apps/spectator/app/game/[id]/_components/CheerTalk/MenuModal/index.tsx
apps/spectator/app/game/[id]/_components/CheerTalk/index.tsx
apps/spectator/app/game/[id]/_components/CheerVS/TeamBox.tsx
apps/spectator/components/LeagueList/index.tsx
apps/spectator/queries/useCheerMutation.ts

- closed #240 
- 응원하기에서 더 이상 음수 데이터를 전송하지 않습니다.
- 응원하기 API를 호출할 때마다 쿼리 캐시를 무효화 하여 최신 데이터로 유지합니다.
- 따라서 cheerCount가 매 응원하기 호출 시 변경됩니다.
- useEffect를 통해 cheerCount가 변경될 때마다 count 상태를 업데이트합니다.
- 이제 더이상 응원하기 호출 시 cheerCount와 count 간의 격차가 발생하지 않습니다.
- 따라서 음수 데이터를 전송하는 경우도 사라집니다.

[FIX] cheerVS 음수 데이터 전송 버그 해결

---

docs/storybook/stories/Spinner.stories.tsx

- #255 
- 베이스 변경 시 코드를 머지하면서 스토리 파일에 argTypes 프로퍼티가 누락된 모양입니다.
- 이를 추가했습니다.

[FIX] 누락된 프로퍼티(argTypes) 추가

---

apps/spectator/app/_components/GameFilter/GameFilter.css.ts
apps/spectator/app/_components/GameFilter/LeagueTeamFilter.tsx
apps/spectator/package.json
packages/ui/src/spinner/spinner.tsx
pnpm-lock.yaml

- closed #259 
- 필터를 클릭 했을 때 화면 가운데로 이동합니다. 
- 드래그를 통해 필터 동작
- 마우스 휠을 통해 횡스크롤 동작
- `@egjs/Flicking`을 사용했을 때 모바일에서 제대로 동작하지 않는 버그가 있었습니다.
- 이에 따라 가로로 길어질 수 있는 대회 팀 목록에 대해서 제한적으로 커스텀 스크롤 이벤트가 적용되어 있던 상황입니다.
- 하지만 드래그 이벤트를 추가로 적용하지 않아서 현재는 웹 브라우저에서 스크롤 이벤트만 적용이 되고 있었습니다.
- 추가로 가로 스크롤을 발생시키기 위해 `shift + mouse wheel`을 동작시켜야 했기 때문에 해당 커맨드를 모르는 사용자의 경우 불편함을 겪을 수 있었습니다.
[embla-carousel](embla-carousel.com), [keen-slider](keen-slider.io) 등의 라이브러리를 이용하여 캐러셀 컴포넌트를 만들어보려 시도했습니다.
하지만 애초에 **캐러셀 혹은 슬라이더**라는 컴포넌트와 우리가 만들고자 하는 필터 컴포넌트의 쓰임새가 달랐기 때문에 라이브러리 내에서 제공하지 않거나, 스펙이 맞지 않는 경우가 많았습니다. 그래서 패키지를 커스텀하거나 일종의 꼼수를 부려 요구사항을 만족하기 위해 시도해보았지만, 말 그대로 꼼수였기 때문에 사이드 이펙트가 발생하기 일쑤였습니다. 
ex) 요소 클릭 시 가운데에 위치하도록 하기 위해 직접 거리를 계산해줘야 하는 문제. 매번 거리를 계산하다 보니 버벅임이 있었음
그래서 해당 방법은 폐기했습니다.
`Element.scrollIntoView()` 메서드를 이용하여 …

[REFACTOR] 필터 클릭 시 화면 가운데로 이동

---

apps/spectator/api/league.ts
apps/spectator/app/_components/GameFilter/LeagueTeamFilter.tsx
apps/spectator/app/page.tsx
apps/spectator/queries/useLeagueDetail.ts
apps/spectator/queries/useLeagueTeams.ts

- closed #267
- 리그 팀을 표시하는 경우 라운드에 포함되지 않은 팀까지 표시할 필요는 없다고 팀 내부적으로 결정되었고, 이에 맞게 API가 수정되었습니다.
- 프론트엔드 팀에서도 이를 반영하여 일부 코드를 수정합니다.
- getLeagueTeam() API의 파라미터로 round 추가
- 현재 선택된 round 정보를 알 수 있도록 useLeagueDetailQuery의 프리패치 부분에서 실제 데이터 패칭 작업을 동시에 수행
- useLeagueTeamQuery()에 round 파라미터 추가
- LeagueTeamFilter 컴포넌트에 round props 추가

[REFACTOR] 리그 팀 목록 필터링 조건(round) 추가

---

docs/storybook/.storybook/preview.tsx
docs/storybook/package.json
docs/storybook/stories/Form.stories.tsx
docs/storybook/stories/Input.stories.tsx
packages/ui/package.json
packages/ui/src/form/form.tsx
packages/ui/src/form/index.ts
packages/ui/src/form/styles.css.ts
packages/ui/src/form/useFormField.ts
packages/ui/src/index.ts
packages/ui/src/input/index.ts
packages/ui/src/input/index.tsx
packages/ui/src/input/input.tsx
packages/ui/src/input/styles.css.ts
pnpm-lock.yaml

- closed #261 
- [shadcn/ui의 Form 컴포넌트](https://ui.shadcn.com/docs/components/form)를 참고하여 추상화 컴포넌트 제작
- 다른 UI 라이브러리와의 호환성을 고려하여 react-hook-form의 `Controller` 컴포넌트(제어 컴포넌트)를 이용한 듯 합니다.
- 하지만 우리는 다른 UI 라이브러리를 사용할 일이 없을 것이라 판단하여 비제어 컴포넌트로 작성해보았습니다.
- [`react-hook-form`](https://react-hook-form.com/get-started)을 사용한 이유는 다음과 같습니다.
- 비제어 컴포넌트를 활용하기 때문에 입력에 따른 렌더링 최적화를 할 수 있습니다.
- 다양한 form 관련 훅을 제공하고 form 요소의 유효성 검사를 용이하게 하여 개발 생산성이 대폭 증대합니다.
- 여기에 [`zod`](https://zod.dev/?id=introduction)라는 스키마 선언 및 유효성 검사 라이브러리를 이용하여 더욱 직관적이고 가독성 좋게 유효성 검사를 할 수 있습니다.
- 자세한 내용은 스토리북을 참고해주세요.
- https://65b76a66edbcddcd871355c6-xqjmicaklw.chromatic.com/?path=/story/hcc-form--default
- Input 컴포넌트나 Button 컴포넌트의 focus, hover 등 사용자 이벤트와 관련한 스타일이 아직 나오지 않아서 가볍게 작성해두었습니다. 추후 수정하면 좋을 것 같습니다.

[FEAT] Form 요소 추가

---

apps/manager/api/auth.ts
packages/api/.eslintrc.cjs
packages/api/package.json
packages/api/src/QueryClientProvider.tsx
packages/api/src/fetcher.ts
packages/api/src/index.ts
packages/api/src/mutations/index.tsx
packages/api/src/mutations/useManagerLogin.ts
packages/api/src/queries/index.tsx
packages/api/src/queries/useLeague.ts
packages/api/src/queries/useLeagues.ts
packages/api/src/queryKey.ts
packages/api/src/types/league.ts
packages/api/src/vite-env.d.ts
packages/api/tsconfig.json
packages/api/vite.config.ts
packages/typescript-config/vite-library.json
pnpm-lock.yaml
turbo.json

- #278 
- `packages/api` 폴더에 API 통신 관련 코드를 이전했습니다.
- 매니저에서 사용되는 일부 `Query`, `Mutation`을 추가하였고, 폴더 구조를 적립했습니다. 
- `Query Keys Factory`의 경우, 객체로 구현이 가능하여 라이브러리를 사용하지 않습니다.
- 매니저 페이지 작업을 하면서 계속해서 파일 추가 예정입니다.
- 현재 [api.hufstreaming.site](https://api.hufstreaming.site)에 CORS 설정이 되어있지 않은 것으로 알고 있습니다. 이와 관련해서도 추후 논의를 해보면 좋겠습니다. (이전에 Suspense 패턴 사용으로 전체 도메인에 대해 풀어놓았던 것으로 기억합니다.)

[FEAT] API 패키지 분리

---

apps/manager/app/league/register/page.css.ts
apps/manager/app/league/register/page.tsx
apps/manager/components/Layout/Navigation/Navigation.css.ts
apps/manager/components/Tip/Tip.css.ts
apps/manager/components/Tip/index.tsx
packages/ui/src/button/styles.css.ts
packages/ui/src/calendar/calendar.tsx
packages/ui/src/calendar/styles.css.ts

- #284 
- #280 에서 폼 디자인 변경으로 인해 신규 대회 만들기 페이지의 디자인이 변경되는 문제가 있었습니다.
- `FormItem`에 존재했던 `marginTop`을 제거하고, 부모 컴포넌트에서 `Gap`으로 관리하도록 변경했습니다.
- <img width="300" alt="image" src="https://github.com/user-attachments/assets/af1be8b3-a565-4db8-b25e-fcc3882647f0">
- `Tip` 컴포넌트가 `register` 뿐만 아니라, `manage` 페이지에서도 사용되기 때문에 매니저 앱의 공통 컴포넌트로 분리했습니다.
- 화면 하단에 고정되도록 설정했습니다. 
- `Calendar` 컴포넌트가 토요일, 일요일 관계 없이 `weekdays`인 경우 모두 빨간색으로 표시되고 있었습니다. 
- 토요일과 일요일의 경계를 확실히 하고자, 토요일의 경우 `colors.accent.priamry` 값을 표시하도록 했습니다.
- 일반적인 캘린더와 요일 순서를 맞추기 위해 `일 월 화 수 목 금 토` 순으로 날짜를 정렬했습니다. 
- <img width="250" alt="image" src="https://github.com/user-attachments/assets/d149196d-b801-4164-95a2-07f53f60a068">

[FIX] 신규 대회 만들기 페이지 디자인 수정

---

apps/manager/app/not-found.css.ts
apps/manager/app/not-found.tsx

- #291 
- 매니저 앱에 404 페이지를 추가했습니다.
- <img width="300" alt="image" src="https://github.com/user-attachments/assets/006635ae-fd9d-4759-a5b9-3144012bf518">
- 해당 페이지에서만 사용되는 버튼 색상(홈 버튼)이 존재해서, 따로 `colorScheme`를 만들지 않고, 스타일 링크로 대체했습니다.

[FEAT] 매니저 404 페이지 구현

---

docs/storybook/stories/Badge.stories.tsx
packages/ui/src/badge/badge.tsx
packages/ui/src/badge/index.ts
packages/ui/src/badge/styles.css.ts
packages/ui/src/index.ts

- #296 
- Badge 컴포넌트를 추가했습니다.
- <img width="89" alt="image" src="https://github.com/user-attachments/assets/0e050c47-47a6-485f-9e95-b44b1c1fe0a0">
- 기본은 `span`으로 작업했고, `asChild`로 버튼 등 이식해서 사용하면 될 것 같습니다.
- `colorScheme`는 `primary`, `accentPrimary`, `secondary`, `alert` 입니다.

[FEAT] Badge 컴포넌트 추가

---

apps/manager/app/_components/MatchOverview/index.tsx
apps/manager/app/league/[leagueId]/_components/LeagueOverview/index.tsx
apps/manager/app/league/[leagueId]/manage/page.tsx
apps/manager/app/league/_components/LeagueCard/index.tsx
apps/manager/app/league/_components/LeagueForm/LeagueForm.tsx
apps/manager/app/league/_components/LeagueForm/types.ts
apps/manager/app/league/register/page.tsx
packages/api/src/fetcher.ts
packages/api/src/mutations/index.tsx
packages/api/src/mutations/useCreateLeague.ts
packages/api/src/mutations/useDeleteLeague.ts
packages/api/src/mutations/useDeleteLeagueTeam.ts
packages/api/src/mutations/useUpdateLeague.ts
packages/api/src/mutations/useUpdateLeagueTeam.ts
packages/api/src/queries/useGamesByLeagueList.ts
packages/api/src/types/league.ts

- #308 
- 구현된 리그 페이지에 API를 연결했습니다. 
- 리그 팀 수정 부분에서 401 오류가 발생하고 있어 해결이 필요합니다.

[FEAT] 매니저 리그 페이지 API 연결

---

apps/manager/app/_components/MatchOverview/index.tsx
apps/manager/app/league/[leagueId]/_components/GameCard/index.tsx
apps/manager/app/league/[leagueId]/page.tsx
apps/manager/app/league/[leagueId]/register-game/_components/lineup-badge/index.tsx
apps/manager/app/league/[leagueId]/register-game/_components/lineup-badge/styles.css.ts
apps/manager/app/league/[leagueId]/register-game/_components/lineup-sheet/index.tsx
apps/manager/app/league/[leagueId]/register-game/_components/lineup-sheet/styles.css.ts
apps/manager/app/league/[leagueId]/register-game/_components/time-input/index.tsx
apps/manager/app/league/[leagueId]/register-game/_components/time-input/styles.css.ts
apps/manager/app/league/[leagueId]/register-game/_constants/index.ts
apps/manager/app/league/[leagueId]/register-game/page.tsx
apps/manager/app/league/[leagueId]/register-game/styles.css.ts
apps/manager/app/league/_components/LeagueCard/index.tsx
apps/manager/app/page.tsx
apps/spectator/app/_components/GameList/GameList.css.ts
apps/spectator/app/_components/GameList/Info.tsx
apps/spectator/constants/configs.ts
packages/api/src/mutations/index.tsx
packages/api/src/mutations/useCreateGames.ts
packages/api/src/queries/index.tsx
packages/api/src/queries/useLeagueTeamDetail.ts
packages/api/src/queryKey.ts
packages/api/src/types/game.ts
packages/api/src/types/team.ts
packages/ui/src/bottom-sheet/styles.css.ts
packages/ui/src/form/styles.css.ts
packages/ui/src/select/select.tsx

- 리그 경기 생성 페이지 추가
- 피그마 상에는 경기 생성 시 라인업 등록 버튼이 표시되도록 되어 있지만 로직 상 불가능하여 일단 제거하고 새로운 페이지로 리다이렉트 시켜야 할 것 같음
- 이유는, 라인업 등록 여부를 판단하기 위해서 리그 경기의 ID를 불러와야 하는데, 경기 생성 페이지에서는 그게 어려움
- 그래서 [gameId]와 같은 다이나믹 라우팅으로 이동시켜야 할 듯
- 제출 버튼을 누르면 401 권한 에러가 발생하고 있는데, 이 부분은 백엔드와 함께 이야기 해서 해결해야 할 것으로 보임

[FEAT] 리그 경기 생성 페이지 추가

---

apps/spectator/app/_components/GameFilter/GameFilter.css.ts
apps/spectator/app/game/[id]/_components/CheerTalk/Form/Form.css.ts
apps/spectator/app/game/[id]/_components/Timeline/Replacement.tsx
apps/spectator/app/game/[id]/_components/Timeline/Score.tsx
apps/spectator/app/layout.css.ts
apps/spectator/app/layout.tsx
apps/spectator/components/layout/Header.tsx
apps/spectator/queries/useGameTeamInfo.ts
packages/styles/src/globals.css.ts

- #319 
- 테마 css가 적용되지 않아 배경이 투명해지는 오류를 수정했습니다.
- 일부 API 변경으로 인해 발생하는 타입 문제를 해결했습니다.

[FIX] 관객 테마 오류 해결

---

apps/manager/app/league/[leagueId]/[gameId]/page.tsx
apps/manager/app/league/[leagueId]/[gameId]/timeline/_components/Form/ReplacementForm.tsx
apps/manager/app/league/[leagueId]/_components/GameForm/GameForm.tsx
apps/manager/app/league/[leagueId]/_components/GameForm/types.ts
apps/manager/app/league/[leagueId]/_components/LeagueOverview/index.tsx
apps/manager/app/league/[leagueId]/_components/LineupSheet/index.tsx
apps/manager/app/league/[leagueId]/manage/page.tsx
apps/manager/app/league/[leagueId]/register-game/page.tsx
apps/manager/constants/games.ts
packages/api/src/queryKey.ts
packages/api/src/types/game.ts
packages/api/src/types/league.ts

- #326
- 경기 생성 및 수정 시 라운드 형식 변경으로 인한 저장 오류를 해결했습니다.
- 선수 DTO 변경으로 인해 빌드가 정상적으로 이루어지지 않는 문제를 수정했습니다.
- 경기 생성 및 수정 시 라운드를 리그의 `maxRound`에 따라 필터(높은 라운드 선택 불가능)되게 변경했습니다.

fix: 경기 수정 시 라운드 타입 불일치 해결

---

apps/manager/app/league/[leagueId]/_components/GameCard/index.tsx
apps/manager/app/league/[leagueId]/_components/GameCard/styles.css.ts
apps/manager/app/league/[leagueId]/_components/LeagueOverview/index.tsx

- #337 
- 리그 상세 페이지에서 '상세정보'를 '편집'으로 변경했습니다.
- 매니저 페이지에서 게임 이름이 보이지 않아 불편해서 게임 이름을 추가했습니다.

chore: 매니저 앱 상세정보 텍스트 변경

---

apps/manager/app/league/[leagueId]/[gameId]/page.tsx
apps/manager/app/league/[leagueId]/_components/GameForm/types.ts
apps/manager/app/league/[leagueId]/_components/TeamForm/types.ts
apps/manager/app/league/[leagueId]/cheer-talk/blocked/page.tsx
apps/manager/app/league/[leagueId]/cheer-talk/page.tsx
apps/manager/app/league/[leagueId]/manage/page.tsx
apps/manager/app/league/[leagueId]/register-game/page.tsx
apps/manager/app/league/[leagueId]/register-team/page.tsx
apps/manager/app/league/[leagueId]/team/[teamId]/page.tsx
apps/manager/app/league/_components/LeagueCard/index.tsx
apps/manager/app/league/_components/LeagueForm/LeagueForm.tsx
apps/manager/app/league/register/page.tsx
apps/manager/constants/games.ts
packages/api/src/mutations/useCreateLeague.ts
packages/api/src/mutations/useDeleteLeague.ts
packages/api/src/mutations/useUpdateLeague.ts

- #343 
- 매니저 앱에서 대회 및 게임 생성, 수정 시 문제가 발생하여 아래와 같은 이슈를 해결했습니다. 
- 게임 시작 시 state = "PLAYING " 값이 넘어가는 문제 해결
- 타인라인 - 연장전 변경 시 경기가 종료되는 문제 해결
- 대회 생성 시 종료일 시간을 "23:59"로 변경
- 경기 생성, 경기 수정, 응원톡 차단, 응원톡 복구, 대회 생성, 대회 수정, 팀 생성, 팀 생성, 팀 수정 페이지에 요청 isPending 핸들링
- 팀 생성 페이지에 선수 등록을 하지 않았을 경우, Toast 출력
- 경기 삭제 시 경기 목록으로 이동
- 대회 생성 시 생성 대회 새로고침 되도록 변경

fix: 매니저 대회 및 게임 생성 오류 수정

---

packages/api/src/mutations/useCreateReplacementTimeline.ts

- #347
- 매니저 타임라인 선수 교체 시, 라인업 및 선발 라인업 선수 캐시를 제거하도록 했습니다.

fix: 타임라인 선수 교체 시 Query 캐시 제거

---

apps/spectator/app/_components/GameList/Info.tsx
apps/spectator/app/_components/GameList/styles.css.ts
apps/spectator/app/game/[id]/_components/CheerTalk/Item/Item.css.ts
apps/spectator/app/game/[id]/_components/CheerTalk/List/List.css.ts
apps/spectator/app/game/[id]/_components/CheerTalk/List/index.tsx
apps/spectator/app/game/[id]/_components/CheerVS/TeamBox.tsx
apps/spectator/app/game/[id]/_components/CheerVS/styles.css.ts
apps/spectator/app/game/[id]/_components/Lineup/index.tsx
apps/spectator/app/game/[id]/_components/Lineup/styles.css.ts

- 이슈 번호 #352 
- 경기 리스트, 응원 카운트, 라인업, 응원톡에 있는 로고 배경 제거했습니다.
- 예정, 종료 뱃지가 분간되도록 습니다.
- 아무런 응원톡이 작성되지 않은 경우 문구가 띄워지게 했습니다.
- 경기가 없는 경우 메세지를 띄우는 작업은 빈 배열 데이터가 온 후 최종 데이터가 오고 있는 상태라 최종 데이터 분간이 안 돼서 학님이 이 부분은 봐주시기로 했습니다.

feat: qa 반영
